name: Notes Application CI Pipeline


on:
    push:
      branches: [main]
    pull_request:
      branches: [main] 
      
jobs:
  code-quality-check:
    runs-on: ubuntu-latest # Runs on latest version of Ubuntu!

    steps:
    - name: Checkout Repository Code  
      uses: actions/checkout@v2 # Checkout the repository code

    - name: Setup Node.js Environment
      uses: actions/setup-node@v2 # Setup Node.js environment
      with:
        node-version: '20.16.0'  # Use Node.js 20.16.0 (latest version that is stable (I have also just updated my own version to 20.16.0 ...))

    - name: Install Dependencies (Project)
     # Install dependencies for the project and go to the src directory
      run: |
        cd src
        npm install

    - name: Run Linting Quality Check
    # Run linting and testing for project
      run: |
        cd src
        npm run test-lint

    - name: Run Unit Tests
    # Running the Unit Tests for the project
      run: |
        cd src
        npm run test-unit
