name: Notes Application CI Pipeline


on:
    push:
      branches: [main]
    pull_request:
      branches: [main] 
      
jobs:
  code-quality-check:
    runs-on: ubuntu-latest # Runs on latest version of Ubuntu!

    steps:
    - name: Checkout Repository Code  
      uses: actions/checkout@v2 # Checkout the repository code

    - name: Setup Node.js Environment
      uses: actions/setup-node@v2 # Setup Node.js environment
      with:
        node-version: '18'  # Use Node.js 18 (latest version that is stable)

    - name: Install Dependencies (Project)
     # Install dependencies for the project and go to the src directory
      run: |
        cd src
        npm install
