name: Notes Application CI Pipeline


on:
    push:
      branches: [main]
    pull_request:
      branches: [main] 
      
jobs:
  code-quality-check:
    runs-on: ubuntu-latest # Runs on latest version of Ubuntu!

    steps:
    - name: Checkout Repository Code  
      uses: actions/checkout@v2 # Checkout the repository code

    - name: Setup Node.js Environment
      uses: actions/setup-node@v2 # Setup Node.js environment

    - name: Install Dependencies (Project)
      run: npm install # Install project dependencies
